

CREATE SCHEMA IF NOT EXISTS public;
SET search_path TO public;


CREATE OR REPLACE FUNCTION public.fn_set_data_atualizacao()
RETURNS TRIGGER AS $$
BEGIN
    NEW.data_atualizacao = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TABLE IF NOT EXISTS public.admcore_pessoa (
    id_pessoa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    nome_social VARCHAR(120),
    cpfcnpj VARCHAR(14) NOT NULL UNIQUE,
    tipo_pessoa CHAR(1) NOT NULL,
    data_nascimento DATE,
    rg VARCHAR(20) UNIQUE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_admcore_pessoa_tipo_pessoa
        CHECK (tipo_pessoa IN ('F', 'J'))
);

CREATE TABLE IF NOT EXISTS public.admcore_cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pessoa BIGINT NOT NULL UNIQUE,
    apelido VARCHAR(60) UNIQUE,
    foto_url VARCHAR(255),
    biografia TEXT,
    status_cliente VARCHAR(20) NOT NULL DEFAULT 'ativo',
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_admcore_cliente_status
        CHECK (status_cliente IN ('ativo', 'bloqueado', 'inativo', 'excluido')),

    CONSTRAINT fk_admcore_cliente_pessoa
        FOREIGN KEY (id_pessoa)
        REFERENCES public.admcore_pessoa(id_pessoa)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admcore_cliente_status
    ON public.admcore_cliente (status_cliente);

CREATE TABLE IF NOT EXISTS public.admcore_clientecontato (
    id_contato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    tipo_contato VARCHAR(20) NOT NULL,
    valor VARCHAR(150) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    verificado BOOLEAN NOT NULL DEFAULT FALSE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_admcore_clientecontato_tipo
        CHECK (tipo_contato IN ('email', 'telefone', 'celular', 'whatsapp')),

    CONSTRAINT uq_admcore_clientecontato
        UNIQUE (id_cliente, tipo_contato, valor),

    CONSTRAINT fk_admcore_clientecontato_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admcore_clientecontato_cliente
    ON public.admcore_clientecontato (id_cliente);

CREATE INDEX IF NOT EXISTS idx_admcore_clientecontato_valor
    ON public.admcore_clientecontato (valor);

CREATE TABLE IF NOT EXISTS public.admcore_endereco (
    id_endereco BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    tipo_endereco VARCHAR(20) NOT NULL DEFAULT 'residencial',
    logradouro VARCHAR(120) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    complemento VARCHAR(80),
    bairro VARCHAR(80) NOT NULL,
    cidade VARCHAR(80) NOT NULL,
    estado CHAR(2) NOT NULL,
    cep CHAR(8) NOT NULL,
    ponto_referencia VARCHAR(150),
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_admcore_endereco_tipo
        CHECK (tipo_endereco IN ('residencial', 'comercial', 'entrega', 'retirada', 'cobranca')),

    CONSTRAINT fk_admcore_endereco_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admcore_endereco_cliente
    ON public.admcore_endereco (id_cliente);

CREATE INDEX IF NOT EXISTS idx_admcore_endereco_cep
    ON public.admcore_endereco (cep);

CREATE INDEX IF NOT EXISTS idx_admcore_endereco_cidade_estado
    ON public.admcore_endereco (cidade, estado);


CREATE TABLE IF NOT EXISTS public.cauth_login (
    id_login BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    email_verificado BOOLEAN NOT NULL DEFAULT FALSE,
    ultimo_login TIMESTAMP,
    status_login VARCHAR(20) NOT NULL DEFAULT 'pendente',
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_cauth_login_status
        CHECK (status_login IN ('ativo', 'bloqueado', 'pendente', 'excluido')),

    CONSTRAINT fk_cauth_login_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cauth_login_email_status
    ON public.cauth_login (email, status_login);


CREATE TABLE IF NOT EXISTS public.marketplace_categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria_pai BIGINT,
    nome VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL UNIQUE,
    descricao TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT fk_marketplace_categoria_pai
        FOREIGN KEY (id_categoria_pai)
        REFERENCES public.marketplace_categoria(id_categoria)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_categoria_pai
    ON public.marketplace_categoria (id_categoria_pai);

CREATE TABLE IF NOT EXISTS public.marketplace_anuncio (
    id_anuncio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vendedor BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    id_endereco_origem BIGINT,
    titulo VARCHAR(140) NOT NULL,
    descricao TEXT NOT NULL,
    condicao_produto VARCHAR(20) NOT NULL DEFAULT 'usado',
    preco DECIMAL(12, 2) NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    aceita_proposta BOOLEAN NOT NULL DEFAULT TRUE,
    tipo_entrega VARCHAR(30) NOT NULL DEFAULT 'combinar',
    status_anuncio VARCHAR(20) NOT NULL DEFAULT 'rascunho',
    visualizacoes INTEGER NOT NULL DEFAULT 0,
    data_publicacao TIMESTAMP,
    data_expiracao TIMESTAMP,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_marketplace_anuncio_condicao
        CHECK (condicao_produto IN ('novo', 'seminovo', 'usado')),

    CONSTRAINT chk_marketplace_anuncio_tipo_entrega
        CHECK (tipo_entrega IN ('combinar', 'retirada', 'correios', 'transportadora', 'digital')),

    CONSTRAINT chk_marketplace_anuncio_status
        CHECK (status_anuncio IN ('rascunho', 'ativo', 'pausado', 'vendido', 'cancelado', 'expirado', 'bloqueado')),

    CONSTRAINT chk_marketplace_anuncio_preco
        CHECK (preco >= 0),

    CONSTRAINT chk_marketplace_anuncio_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT chk_marketplace_anuncio_visualizacoes
        CHECK (visualizacoes >= 0),

    CONSTRAINT fk_marketplace_anuncio_vendedor
        FOREIGN KEY (id_vendedor)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_anuncio_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES public.marketplace_categoria(id_categoria)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_anuncio_endereco_origem
        FOREIGN KEY (id_endereco_origem)
        REFERENCES public.admcore_endereco(id_endereco)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_anuncio_vendedor_status
    ON public.marketplace_anuncio (id_vendedor, status_anuncio);

CREATE INDEX IF NOT EXISTS idx_marketplace_anuncio_categoria_status
    ON public.marketplace_anuncio (id_categoria, status_anuncio);

CREATE INDEX IF NOT EXISTS idx_marketplace_anuncio_preco
    ON public.marketplace_anuncio (preco);

CREATE INDEX IF NOT EXISTS idx_marketplace_anuncio_publicacao
    ON public.marketplace_anuncio (data_publicacao);

CREATE TABLE IF NOT EXISTS public.marketplace_anunciofoto (
    id_foto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_anuncio BIGINT NOT NULL,
    url_foto VARCHAR(255) NOT NULL,
    ordem INTEGER NOT NULL DEFAULT 1,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_marketplace_anunciofoto_ordem
        CHECK (ordem > 0),

    CONSTRAINT fk_marketplace_anunciofoto_anuncio
        FOREIGN KEY (id_anuncio)
        REFERENCES public.marketplace_anuncio(id_anuncio)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_anunciofoto_anuncio
    ON public.marketplace_anunciofoto (id_anuncio);

CREATE TABLE IF NOT EXISTS public.marketplace_anuncioatributo (
    id_atributo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_anuncio BIGINT NOT NULL,
    chave VARCHAR(80) NOT NULL,
    valor VARCHAR(150) NOT NULL,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_marketplace_anuncioatributo
        UNIQUE (id_anuncio, chave),

    CONSTRAINT fk_marketplace_anuncioatributo_anuncio
        FOREIGN KEY (id_anuncio)
        REFERENCES public.marketplace_anuncio(id_anuncio)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.marketplace_favorito (
    id_favorito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    id_anuncio BIGINT NOT NULL,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_marketplace_favorito_cliente_anuncio
        UNIQUE (id_cliente, id_anuncio),

    CONSTRAINT fk_marketplace_favorito_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_favorito_anuncio
        FOREIGN KEY (id_anuncio)
        REFERENCES public.marketplace_anuncio(id_anuncio)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_favorito_cliente
    ON public.marketplace_favorito (id_cliente);

CREATE TABLE IF NOT EXISTS public.marketplace_conversa (
    id_conversa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_anuncio BIGINT NOT NULL,
    id_comprador BIGINT NOT NULL,
    id_vendedor BIGINT NOT NULL,
    status_conversa VARCHAR(20) NOT NULL DEFAULT 'aberta',
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_marketplace_conversa_status
        CHECK (status_conversa IN ('aberta', 'arquivada', 'bloqueada')),

    CONSTRAINT chk_marketplace_conversa_usuarios_diferentes
        CHECK (id_comprador <> id_vendedor),

    CONSTRAINT uq_marketplace_conversa_anuncio_comprador
        UNIQUE (id_anuncio, id_comprador),

    CONSTRAINT fk_marketplace_conversa_anuncio
        FOREIGN KEY (id_anuncio)
        REFERENCES public.marketplace_anuncio(id_anuncio)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_conversa_comprador
        FOREIGN KEY (id_comprador)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_conversa_vendedor
        FOREIGN KEY (id_vendedor)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_conversa_comprador
    ON public.marketplace_conversa (id_comprador);

CREATE INDEX IF NOT EXISTS idx_marketplace_conversa_vendedor
    ON public.marketplace_conversa (id_vendedor);

CREATE TABLE IF NOT EXISTS public.marketplace_mensagem (
    id_mensagem BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_conversa BIGINT NOT NULL,
    id_remetente BIGINT NOT NULL,
    mensagem TEXT NOT NULL,
    lida BOOLEAN NOT NULL DEFAULT FALSE,
    data_leitura TIMESTAMP,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_marketplace_mensagem_conversa
        FOREIGN KEY (id_conversa)
        REFERENCES public.marketplace_conversa(id_conversa)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_mensagem_remetente
        FOREIGN KEY (id_remetente)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_mensagem_conversa_data
    ON public.marketplace_mensagem (id_conversa, data_cadastro);

CREATE INDEX IF NOT EXISTS idx_marketplace_mensagem_remetente
    ON public.marketplace_mensagem (id_remetente);

CREATE TABLE IF NOT EXISTS public.marketplace_carrinho (
    id_carrinho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    status_carrinho VARCHAR(20) NOT NULL DEFAULT 'ativo',
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_marketplace_carrinho_status
        CHECK (status_carrinho IN ('ativo', 'convertido', 'abandonado', 'cancelado')),

    CONSTRAINT fk_marketplace_carrinho_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_carrinho_cliente_status
    ON public.marketplace_carrinho (id_cliente, status_carrinho);

CREATE TABLE IF NOT EXISTS public.marketplace_carrinhoitem (
    id_carrinho_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrinho BIGINT NOT NULL,
    id_anuncio BIGINT NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT uq_marketplace_carrinhoitem
        UNIQUE (id_carrinho, id_anuncio),

    CONSTRAINT chk_marketplace_carrinhoitem_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT fk_marketplace_carrinhoitem_carrinho
        FOREIGN KEY (id_carrinho)
        REFERENCES public.marketplace_carrinho(id_carrinho)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_carrinhoitem_anuncio
        FOREIGN KEY (id_anuncio)
        REFERENCES public.marketplace_anuncio(id_anuncio)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_carrinhoitem_anuncio
    ON public.marketplace_carrinhoitem (id_anuncio);

CREATE TABLE IF NOT EXISTS public.marketplace_pedido (
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_pedido VARCHAR(40) NOT NULL UNIQUE,
    id_comprador BIGINT NOT NULL,
    id_vendedor BIGINT NOT NULL,
    id_endereco_entrega BIGINT,
    status_pedido VARCHAR(30) NOT NULL DEFAULT 'criado',
    subtotal DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    valor_frete DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    valor_desconto DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    valor_taxa_plataforma DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    total DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    observacao TEXT,
    data_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_marketplace_pedido_status
        CHECK (status_pedido IN (
            'criado',
            'aguardando_pagamento',
            'pago',
            'em_preparacao',
            'enviado',
            'entregue',
            'concluido',
            'cancelado',
            'reembolsado',
            'disputa'
        )),

    CONSTRAINT chk_marketplace_pedido_usuarios_diferentes
        CHECK (id_comprador <> id_vendedor),

    CONSTRAINT chk_marketplace_pedido_valores
        CHECK (
            subtotal >= 0
            AND valor_frete >= 0
            AND valor_desconto >= 0
            AND valor_taxa_plataforma >= 0
            AND total >= 0
        ),

    CONSTRAINT fk_marketplace_pedido_comprador
        FOREIGN KEY (id_comprador)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_pedido_vendedor
        FOREIGN KEY (id_vendedor)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_pedido_endereco_entrega
        FOREIGN KEY (id_endereco_entrega)
        REFERENCES public.admcore_endereco(id_endereco)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_pedido_comprador_status
    ON public.marketplace_pedido (id_comprador, status_pedido);

CREATE INDEX IF NOT EXISTS idx_marketplace_pedido_vendedor_status
    ON public.marketplace_pedido (id_vendedor, status_pedido);

CREATE INDEX IF NOT EXISTS idx_marketplace_pedido_data
    ON public.marketplace_pedido (data_pedido);

CREATE TABLE IF NOT EXISTS public.marketplace_pedidoitem (
    id_pedido_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL,
    id_anuncio BIGINT NOT NULL,
    titulo_snapshot VARCHAR(140) NOT NULL,
    preco_unitario_snapshot DECIMAL(12, 2) NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    total_item DECIMAL(12, 2) NOT NULL,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_marketplace_pedidoitem
        UNIQUE (id_pedido, id_anuncio),

    CONSTRAINT chk_marketplace_pedidoitem_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT chk_marketplace_pedidoitem_valores
        CHECK (preco_unitario_snapshot >= 0 AND total_item >= 0),

    CONSTRAINT fk_marketplace_pedidoitem_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES public.marketplace_pedido(id_pedido)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_pedidoitem_anuncio
        FOREIGN KEY (id_anuncio)
        REFERENCES public.marketplace_anuncio(id_anuncio)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_pedidoitem_anuncio
    ON public.marketplace_pedidoitem (id_anuncio);


CREATE TABLE IF NOT EXISTS public.financeiro_formapagamento (
    id_forma_pagamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nome VARCHAR(80) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.financeiro_bandeiracartao (
    id_bandeira_cartao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nome VARCHAR(60) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.financeiro_cartaocliente (
    id_cartao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    id_bandeira_cartao BIGINT NOT NULL,
    gateway VARCHAR(60) NOT NULL,
    token_gateway VARCHAR(255) NOT NULL,
    titular_nome VARCHAR(120),
    ultimos4 CHAR(4) NOT NULL,
    mes_expiracao SMALLINT NOT NULL,
    ano_expiracao SMALLINT NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    status_cartao VARCHAR(20) NOT NULL DEFAULT 'ativo',
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT uq_financeiro_cartaocliente_token
        UNIQUE (gateway, token_gateway),

    CONSTRAINT chk_financeiro_cartaocliente_mes
        CHECK (mes_expiracao BETWEEN 1 AND 12),

    CONSTRAINT chk_financeiro_cartaocliente_ano
        CHECK (ano_expiracao >= 2000),

    CONSTRAINT chk_financeiro_cartaocliente_status
        CHECK (status_cartao IN ('ativo', 'expirado', 'removido', 'bloqueado')),

    CONSTRAINT fk_financeiro_cartaocliente_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_financeiro_cartaocliente_bandeira
        FOREIGN KEY (id_bandeira_cartao)
        REFERENCES public.financeiro_bandeiracartao(id_bandeira_cartao)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_financeiro_cartaocliente_cliente
    ON public.financeiro_cartaocliente (id_cliente);

CREATE INDEX IF NOT EXISTS idx_financeiro_cartaocliente_bandeira
    ON public.financeiro_cartaocliente (id_bandeira_cartao);

CREATE TABLE IF NOT EXISTS public.financeiro_pagamento (
    id_pagamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL,
    id_forma_pagamento BIGINT NOT NULL,
    id_cartao BIGINT,
    valor DECIMAL(12, 2) NOT NULL,
    parcelas SMALLINT NOT NULL DEFAULT 1,
    status_pagamento VARCHAR(20) NOT NULL DEFAULT 'pendente',
    gateway VARCHAR(60),
    gateway_pagamento_id VARCHAR(120),
    nsu VARCHAR(80),
    tid VARCHAR(80),
    codigo_autorizacao VARCHAR(80),
    cartao_bandeira_snapshot VARCHAR(30),
    cartao_ultimos4_snapshot CHAR(4),
    data_autorizacao TIMESTAMP,
    data_captura TIMESTAMP,
    data_pagamento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_financeiro_pagamento_status
        CHECK (status_pagamento IN ('pendente', 'autorizado', 'aprovado', 'recusado', 'cancelado', 'estornado')),

    CONSTRAINT chk_financeiro_pagamento_valor
        CHECK (valor >= 0),

    CONSTRAINT chk_financeiro_pagamento_parcelas
        CHECK (parcelas >= 1),

    CONSTRAINT fk_financeiro_pagamento_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES public.marketplace_pedido(id_pedido)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_financeiro_pagamento_forma
        FOREIGN KEY (id_forma_pagamento)
        REFERENCES public.financeiro_formapagamento(id_forma_pagamento)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_financeiro_pagamento_cartao
        FOREIGN KEY (id_cartao)
        REFERENCES public.financeiro_cartaocliente(id_cartao)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_financeiro_pagamento_pedido_status
    ON public.financeiro_pagamento (id_pedido, status_pagamento);

CREATE INDEX IF NOT EXISTS idx_financeiro_pagamento_gateway
    ON public.financeiro_pagamento (gateway, gateway_pagamento_id);

CREATE TABLE IF NOT EXISTS public.financeiro_pagamentoevento (
    id_pagamento_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pagamento BIGINT NOT NULL,
    status_pagamento VARCHAR(20) NOT NULL,
    mensagem VARCHAR(255),
    payload_gateway JSONB,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_financeiro_pagamentoevento_status
        CHECK (status_pagamento IN ('pendente', 'autorizado', 'aprovado', 'recusado', 'cancelado', 'estornado')),

    CONSTRAINT fk_financeiro_pagamentoevento_pagamento
        FOREIGN KEY (id_pagamento)
        REFERENCES public.financeiro_pagamento(id_pagamento)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_financeiro_pagamentoevento_pagamento
    ON public.financeiro_pagamentoevento (id_pagamento);

CREATE TABLE IF NOT EXISTS public.financeiro_recebedor (
    id_recebedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL UNIQUE,
    gateway VARCHAR(60) NOT NULL,
    gateway_recebedor_id VARCHAR(120) NOT NULL,
    tipo_recebedor VARCHAR(20) NOT NULL,
    chave_pix_mascarada VARCHAR(120),
    banco_codigo VARCHAR(10),
    agencia VARCHAR(20),
    conta_ultimos4 CHAR(4),
    status_recebedor VARCHAR(20) NOT NULL DEFAULT 'pendente',
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT uq_financeiro_recebedor_gateway
        UNIQUE (gateway, gateway_recebedor_id),

    CONSTRAINT chk_financeiro_recebedor_tipo
        CHECK (tipo_recebedor IN ('pessoa_fisica', 'pessoa_juridica')),

    CONSTRAINT chk_financeiro_recebedor_status
        CHECK (status_recebedor IN ('pendente', 'ativo', 'bloqueado', 'reprovado')),

    CONSTRAINT fk_financeiro_recebedor_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.financeiro_repasse (
    id_repasse BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL,
    id_vendedor BIGINT NOT NULL,
    id_recebedor BIGINT,
    valor_bruto DECIMAL(12, 2) NOT NULL,
    valor_taxa_plataforma DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    valor_liquido DECIMAL(12, 2) NOT NULL,
    status_repasse VARCHAR(20) NOT NULL DEFAULT 'pendente',
    data_prevista TIMESTAMP,
    data_pagamento TIMESTAMP,
    gateway_repasse_id VARCHAR(120),
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_financeiro_repasse_status
        CHECK (status_repasse IN ('pendente', 'liberado', 'pago', 'cancelado', 'bloqueado')),

    CONSTRAINT chk_financeiro_repasse_valores
        CHECK (valor_bruto >= 0 AND valor_taxa_plataforma >= 0 AND valor_liquido >= 0),

    CONSTRAINT fk_financeiro_repasse_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES public.marketplace_pedido(id_pedido)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_financeiro_repasse_vendedor
        FOREIGN KEY (id_vendedor)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_financeiro_repasse_recebedor
        FOREIGN KEY (id_recebedor)
        REFERENCES public.financeiro_recebedor(id_recebedor)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_financeiro_repasse_vendedor_status
    ON public.financeiro_repasse (id_vendedor, status_repasse);

CREATE INDEX IF NOT EXISTS idx_financeiro_repasse_pedido
    ON public.financeiro_repasse (id_pedido);


CREATE TABLE IF NOT EXISTS public.logistica_envio (
    id_envio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL UNIQUE,
    id_endereco_origem BIGINT,
    id_endereco_destino BIGINT,
    modalidade_envio VARCHAR(30) NOT NULL DEFAULT 'combinar',
    transportadora VARCHAR(100),
    codigo_rastreamento VARCHAR(80),
    valor_frete DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    status_envio VARCHAR(20) NOT NULL DEFAULT 'pendente',
    data_postagem TIMESTAMP,
    data_entrega TIMESTAMP,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_logistica_envio_modalidade
        CHECK (modalidade_envio IN ('combinar', 'retirada', 'correios', 'transportadora', 'digital')),

    CONSTRAINT chk_logistica_envio_status
        CHECK (status_envio IN ('pendente', 'preparando', 'postado', 'em_transito', 'entregue', 'cancelado')),

    CONSTRAINT chk_logistica_envio_valor_frete
        CHECK (valor_frete >= 0),

    CONSTRAINT fk_logistica_envio_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES public.marketplace_pedido(id_pedido)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_logistica_envio_endereco_origem
        FOREIGN KEY (id_endereco_origem)
        REFERENCES public.admcore_endereco(id_endereco)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    CONSTRAINT fk_logistica_envio_endereco_destino
        FOREIGN KEY (id_endereco_destino)
        REFERENCES public.admcore_endereco(id_endereco)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_logistica_envio_status
    ON public.logistica_envio (status_envio);

CREATE INDEX IF NOT EXISTS idx_logistica_envio_rastreamento
    ON public.logistica_envio (codigo_rastreamento);


CREATE TABLE IF NOT EXISTS public.marketplace_avaliacao (
    id_avaliacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL,
    id_avaliador BIGINT NOT NULL,
    id_avaliado BIGINT NOT NULL,
    papel_avaliado VARCHAR(20) NOT NULL,
    nota SMALLINT NOT NULL,
    comentario TEXT,
    data_avaliacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_marketplace_avaliacao_pedido_usuarios
        UNIQUE (id_pedido, id_avaliador, id_avaliado),

    CONSTRAINT chk_marketplace_avaliacao_papel
        CHECK (papel_avaliado IN ('comprador', 'vendedor')),

    CONSTRAINT chk_marketplace_avaliacao_nota
        CHECK (nota BETWEEN 1 AND 5),

    CONSTRAINT chk_marketplace_avaliacao_usuarios_diferentes
        CHECK (id_avaliador <> id_avaliado),

    CONSTRAINT fk_marketplace_avaliacao_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES public.marketplace_pedido(id_pedido)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_avaliacao_avaliador
        FOREIGN KEY (id_avaliador)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_avaliacao_avaliado
        FOREIGN KEY (id_avaliado)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_avaliacao_avaliado
    ON public.marketplace_avaliacao (id_avaliado);

CREATE TABLE IF NOT EXISTS public.marketplace_denuncia (
    id_denuncia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_denunciante BIGINT NOT NULL,
    id_cliente_denunciado BIGINT,
    id_anuncio BIGINT,
    motivo VARCHAR(30) NOT NULL,
    descricao TEXT,
    status_denuncia VARCHAR(20) NOT NULL DEFAULT 'aberta',
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT chk_marketplace_denuncia_motivo
        CHECK (motivo IN ('fraude', 'produto_proibido', 'ofensa', 'spam', 'golpe', 'outro')),

    CONSTRAINT chk_marketplace_denuncia_status
        CHECK (status_denuncia IN ('aberta', 'em_analise', 'procedente', 'improcedente', 'encerrada')),

    CONSTRAINT chk_marketplace_denuncia_alvo
        CHECK (id_cliente_denunciado IS NOT NULL OR id_anuncio IS NOT NULL),

    CONSTRAINT fk_marketplace_denuncia_denunciante
        FOREIGN KEY (id_denunciante)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_denuncia_cliente_denunciado
        FOREIGN KEY (id_cliente_denunciado)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_denuncia_anuncio
        FOREIGN KEY (id_anuncio)
        REFERENCES public.marketplace_anuncio(id_anuncio)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_denuncia_status
    ON public.marketplace_denuncia (status_denuncia);

CREATE INDEX IF NOT EXISTS idx_marketplace_denuncia_anuncio
    ON public.marketplace_denuncia (id_anuncio);

CREATE TABLE IF NOT EXISTS public.marketplace_cupom (
    id_cupom BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    tipo_desconto VARCHAR(20) NOT NULL,
    valor_desconto DECIMAL(12, 2) NOT NULL,
    valor_minimo_pedido DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    data_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_validade TIMESTAMP NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_marketplace_cupom_tipo
        CHECK (tipo_desconto IN ('percentual', 'valor_fixo')),

    CONSTRAINT chk_marketplace_cupom_valores
        CHECK (valor_desconto >= 0 AND valor_minimo_pedido >= 0)
);

CREATE TABLE IF NOT EXISTS public.marketplace_pedidocupom (
    id_pedido BIGINT NOT NULL,
    id_cupom BIGINT NOT NULL,
    valor_desconto_aplicado DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id_pedido, id_cupom),

    CONSTRAINT chk_marketplace_pedidocupom_valor
        CHECK (valor_desconto_aplicado >= 0),

    CONSTRAINT fk_marketplace_pedidocupom_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES public.marketplace_pedido(id_pedido)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_marketplace_pedidocupom_cupom
        FOREIGN KEY (id_cupom)
        REFERENCES public.marketplace_cupom(id_cupom)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS public.history_historico_status_anuncio (
    id_historico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_anuncio BIGINT NOT NULL,
    status_anterior VARCHAR(20),
    status_novo VARCHAR(20) NOT NULL,
    id_cliente_responsavel BIGINT,
    observacao VARCHAR(255),
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_history_historico_status_anuncio_anterior
        CHECK (status_anterior IS NULL OR status_anterior IN ('rascunho', 'ativo', 'pausado', 'vendido', 'cancelado', 'expirado', 'bloqueado')),

    CONSTRAINT chk_history_historico_status_anuncio_novo
        CHECK (status_novo IN ('rascunho', 'ativo', 'pausado', 'vendido', 'cancelado', 'expirado', 'bloqueado')),

    CONSTRAINT fk_history_historico_status_anuncio_anuncio
        FOREIGN KEY (id_anuncio)
        REFERENCES public.marketplace_anuncio(id_anuncio)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_history_historico_status_anuncio_cliente
        FOREIGN KEY (id_cliente_responsavel)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_history_historico_status_anuncio
    ON public.history_historico_status_anuncio (id_anuncio, data_cadastro);

CREATE TABLE IF NOT EXISTS public.history_historico_status_pedido (
    id_historico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL,
    status_anterior VARCHAR(30),
    status_novo VARCHAR(30) NOT NULL,
    id_cliente_responsavel BIGINT,
    observacao VARCHAR(255),
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_history_historico_status_pedido_anterior
        CHECK (status_anterior IS NULL OR status_anterior IN (
            'criado', 'aguardando_pagamento', 'pago', 'em_preparacao',
            'enviado', 'entregue', 'concluido', 'cancelado', 'reembolsado', 'disputa'
        )),

    CONSTRAINT chk_history_historico_status_pedido_novo
        CHECK (status_novo IN (
            'criado', 'aguardando_pagamento', 'pago', 'em_preparacao',
            'enviado', 'entregue', 'concluido', 'cancelado', 'reembolsado', 'disputa'
        )),

    CONSTRAINT fk_history_historico_status_pedido_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES public.marketplace_pedido(id_pedido)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_history_historico_status_pedido_cliente
        FOREIGN KEY (id_cliente_responsavel)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_history_historico_status_pedido
    ON public.history_historico_status_pedido (id_pedido, data_cadastro);

CREATE TABLE IF NOT EXISTS public.history_historico_status_pagamento (
    id_historico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pagamento BIGINT NOT NULL,
    status_anterior VARCHAR(20),
    status_novo VARCHAR(20) NOT NULL,
    observacao VARCHAR(255),
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_history_historico_status_pagamento_anterior
        CHECK (status_anterior IS NULL OR status_anterior IN ('pendente', 'autorizado', 'aprovado', 'recusado', 'cancelado', 'estornado')),

    CONSTRAINT chk_history_historico_status_pagamento_novo
        CHECK (status_novo IN ('pendente', 'autorizado', 'aprovado', 'recusado', 'cancelado', 'estornado')),

    CONSTRAINT fk_history_historico_status_pagamento_pagamento
        FOREIGN KEY (id_pagamento)
        REFERENCES public.financeiro_pagamento(id_pagamento)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_history_historico_status_pagamento
    ON public.history_historico_status_pagamento (id_pagamento, data_cadastro);

CREATE TABLE IF NOT EXISTS public.history_historico_status_envio (
    id_historico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_envio BIGINT NOT NULL,
    status_anterior VARCHAR(20),
    status_novo VARCHAR(20) NOT NULL,
    observacao VARCHAR(255),
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_history_historico_status_envio_anterior
        CHECK (status_anterior IS NULL OR status_anterior IN ('pendente', 'preparando', 'postado', 'em_transito', 'entregue', 'cancelado')),

    CONSTRAINT chk_history_historico_status_envio_novo
        CHECK (status_novo IN ('pendente', 'preparando', 'postado', 'em_transito', 'entregue', 'cancelado')),

    CONSTRAINT fk_history_historico_status_envio_envio
        FOREIGN KEY (id_envio)
        REFERENCES public.logistica_envio(id_envio)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_history_historico_status_envio
    ON public.history_historico_status_envio (id_envio, data_cadastro);

CREATE TABLE IF NOT EXISTS public.history_auditoria (
    id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela VARCHAR(100) NOT NULL,
    id_registro BIGINT NOT NULL,
    acao VARCHAR(10) NOT NULL,
    id_cliente_responsavel BIGINT,
    dados_anteriores JSONB,
    dados_novos JSONB,
    ip_origem VARCHAR(45),
    user_agent VARCHAR(255),
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_history_auditoria_acao
        CHECK (acao IN ('insert', 'update', 'delete')),

    CONSTRAINT fk_history_auditoria_cliente
        FOREIGN KEY (id_cliente_responsavel)
        REFERENCES public.admcore_cliente(id_cliente)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_history_auditoria_tabela_registro
    ON public.history_auditoria (tabela, id_registro);

CREATE INDEX IF NOT EXISTS idx_history_auditoria_data
    ON public.history_auditoria (data_cadastro);


DROP TRIGGER IF EXISTS tr_admcore_pessoa_set_data_atualizacao ON public.admcore_pessoa;
CREATE TRIGGER tr_admcore_pessoa_set_data_atualizacao
BEFORE UPDATE ON public.admcore_pessoa
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_admcore_cliente_set_data_atualizacao ON public.admcore_cliente;
CREATE TRIGGER tr_admcore_cliente_set_data_atualizacao
BEFORE UPDATE ON public.admcore_cliente
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_admcore_clientecontato_set_data_atualizacao ON public.admcore_clientecontato;
CREATE TRIGGER tr_admcore_clientecontato_set_data_atualizacao
BEFORE UPDATE ON public.admcore_clientecontato
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_admcore_endereco_set_data_atualizacao ON public.admcore_endereco;
CREATE TRIGGER tr_admcore_endereco_set_data_atualizacao
BEFORE UPDATE ON public.admcore_endereco
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_cauth_login_set_data_atualizacao ON public.cauth_login;
CREATE TRIGGER tr_cauth_login_set_data_atualizacao
BEFORE UPDATE ON public.cauth_login
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_marketplace_categoria_set_data_atualizacao ON public.marketplace_categoria;
CREATE TRIGGER tr_marketplace_categoria_set_data_atualizacao
BEFORE UPDATE ON public.marketplace_categoria
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_marketplace_anuncio_set_data_atualizacao ON public.marketplace_anuncio;
CREATE TRIGGER tr_marketplace_anuncio_set_data_atualizacao
BEFORE UPDATE ON public.marketplace_anuncio
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_marketplace_conversa_set_data_atualizacao ON public.marketplace_conversa;
CREATE TRIGGER tr_marketplace_conversa_set_data_atualizacao
BEFORE UPDATE ON public.marketplace_conversa
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_marketplace_carrinho_set_data_atualizacao ON public.marketplace_carrinho;
CREATE TRIGGER tr_marketplace_carrinho_set_data_atualizacao
BEFORE UPDATE ON public.marketplace_carrinho
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_marketplace_carrinhoitem_set_data_atualizacao ON public.marketplace_carrinhoitem;
CREATE TRIGGER tr_marketplace_carrinhoitem_set_data_atualizacao
BEFORE UPDATE ON public.marketplace_carrinhoitem
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_marketplace_pedido_set_data_atualizacao ON public.marketplace_pedido;
CREATE TRIGGER tr_marketplace_pedido_set_data_atualizacao
BEFORE UPDATE ON public.marketplace_pedido
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_financeiro_cartaocliente_set_data_atualizacao ON public.financeiro_cartaocliente;
CREATE TRIGGER tr_financeiro_cartaocliente_set_data_atualizacao
BEFORE UPDATE ON public.financeiro_cartaocliente
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_financeiro_pagamento_set_data_atualizacao ON public.financeiro_pagamento;
CREATE TRIGGER tr_financeiro_pagamento_set_data_atualizacao
BEFORE UPDATE ON public.financeiro_pagamento
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_financeiro_recebedor_set_data_atualizacao ON public.financeiro_recebedor;
CREATE TRIGGER tr_financeiro_recebedor_set_data_atualizacao
BEFORE UPDATE ON public.financeiro_recebedor
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_financeiro_repasse_set_data_atualizacao ON public.financeiro_repasse;
CREATE TRIGGER tr_financeiro_repasse_set_data_atualizacao
BEFORE UPDATE ON public.financeiro_repasse
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_logistica_envio_set_data_atualizacao ON public.logistica_envio;
CREATE TRIGGER tr_logistica_envio_set_data_atualizacao
BEFORE UPDATE ON public.logistica_envio
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();

DROP TRIGGER IF EXISTS tr_marketplace_denuncia_set_data_atualizacao ON public.marketplace_denuncia;
CREATE TRIGGER tr_marketplace_denuncia_set_data_atualizacao
BEFORE UPDATE ON public.marketplace_denuncia
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_data_atualizacao();


INSERT INTO public.financeiro_formapagamento (codigo, nome) VALUES
('cartao_credito', 'Cartão de crédito'),
('cartao_debito', 'Cartão de débito'),
('pix', 'Pix'),
('boleto', 'Boleto'),
('saldo_carteira', 'Saldo em carteira')
ON CONFLICT (codigo) DO UPDATE
SET
    nome = EXCLUDED.nome,
    ativo = TRUE;

INSERT INTO public.financeiro_bandeiracartao (codigo, nome) VALUES
('visa', 'Visa'),
('mastercard', 'Mastercard'),
('elo', 'Elo'),
('amex', 'American Express'),
('hipercard', 'Hipercard'),
('diners', 'Diners Club'),
('discover', 'Discover'),
('outros', 'Outros')
ON CONFLICT (codigo) DO UPDATE
SET
    nome = EXCLUDED.nome,
    ativo = TRUE;

